### ISSUE TITLE
[!!] Archive listing

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-sitemap#2]
It's really long. When People are scrolling through, we want it to be clear that they're in archive section. Maybe add some visual treatment for the Archive section -- maybe just in an standard box?

*or* Possibly we don't include the Archive documents in the sitemap, and have them listed separately only?
pro: makes sitemap page simplier
con: can't do "find on page" on one page to find all docs.

**Comment by yatil** [comment]
* [ ] Archive on the sitemap
* [ ] Expand/Collapse
* [ ] Put retired/archived treatment on the section

**Comment by yatil** [comment]
For the beta I have put only the items in the navigation onto the sitemap for now. We can easily amend it and add expand/collapse during the beta.

**Comment by yatil** [comment]
https://w3c.github.io/wai-website/sitemap/

**Comment by slhenry** [comment]
Yes, there were more things in the Site Map that I created than are in the main nav.  Would like those included before "launch".

**Comment by yatil** [comment]
… which is what I said above :-D

**Comment by yatil** [comment]
Just updated the sitemap

https://github.com/w3c/wai-sitemap/commit/f99a4b0a3197b1d82c66619aa24bafbcd1ce7584

Fixed linking of the individual items and also commented our `@@` using `{% comment %}…{% endcomment %}` – That way it is not even in the generated HTML :-)

**Comment by slhenry** [comment]
I don't see a different visual treatment for that section, but I think it's OK since we have "Archived" in the sub-heads.

**Comment by yatil** [comment]
@slhenry It is in the expand/collapse on the bottom… I can add more treatment.

**Comment by slhenry** [comment]
I don't think worth the time and effort right now. it's wayyyy looooow priority!
