### ISSUE TITLE
needs misc cleanup

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-sitemap#4]
shawn &/or eric -- whoever gets to it first :-)

**Comment by yatil** [comment]
Describe “misc” to me. What is messy?

**Comment by slhenry** [comment]
There are some @@s and that kind of thing -- content, not design or code I think.

**Comment by yatil** [comment]
FWIW I fixed several links yesterday and commented out the @@ so they don’t show up on the website (especially weird when inside a link :-D).

https://github.com/w3c/wai-sitemap/commit/a76ea4ed0c7faac861c1ba6eaab5424922a6c95b

**Comment by slhenry** [comment]
links need fixing, e.g., showing "(in English)" in the roles section
